// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxfgnnecmhmvbvzqheba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZmdubmVjbWhtdmJ2enFoZWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDE0MDEsImV4cCI6MjA2NDgxNzQwMX0.Y9KVzEwmkurSKHh_1NqzGVFyylpP4cR5I8N_G05OKkg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);